### ISSUE TITLE
Switch to address book concept instead of holding the address inside the artifact

### ISSUE THREAD

**Issue by H34D** [oceanprotocol/dori#22]
## Introduction

Back in the days where smart contracts were not upgradable it was a good idea to store the address of the contract close to its ABI. With upgradability we have many more information to store for an contract than just the address on the specific network. We have to store a `proxy` address as well as `n` installation addresses of the contract logic. We now version on the artifact level which leads to many copies of the same ABI for the different networks, resulting in a huge package (artifacts folder is now 1.4 Megabytes). 

The current way of doing this has the following challenges:

- Artifacts folder huge
- No separation of concern ABI/installation
- Many networks
- Many installations on each network with forgetting the previous installation
- No way to build rollback functionality for a contract

## Problem 

Right now we have this structure, based on one single contract:

`Dispenser.duero.json` contains:
- the version number (whilst we version this via the package managers anyways)
- the ABI of a specific version 
- the bytecode of the contract (for testing)
- the proxy address of the duero network
- the (latest) implementation address of the duero network

This leads to:

- `Dispenser.duero.json` for the duero network
- `Dispenser.nile.json` for the nile network
- `Dispenser.pacific.json` for the pacific network

on persistent blockchains.

as well as:

- `Dispenser.spree.json` for the spree network only living in `barge`
- `Dispenser.development.json` for the development ganache network only living in localhost

All these have to be copied around to be used in `barge` or other applications.

## Proposal

Split Build and installation as good as possible.

Create artifacts like `Dispenser.json` that will contain the contract information like:

* the version number
* the ABI of a specific version 
* the bytecode of the contract (for testing)

and version it over the package manager. This will remove the requirement for copying around artifacts on the `spree` network. 

Create an address book that contains all the installation informations:

```json
{
  "spree": {
    "AccessSecretStoreCondition": {
      "v0.11.1": {
        "address": "0x123",
        "implementation": "0x345"
      }
    }
  },
  "duero": {
  },
  "nile": {
  },
  "pacific": {
  }
}
```

this address book will be created (deploy) and updated (upgrade) by `dori` and would need to be copied around in case of the `spree` network. But it can be more comprehensive and more dense than keeping the addresses in the artifacts. 

It is the task for the consumer to evaluate the current version of the contract and fetch the address from the address book on the right network. 

### Additional Ideas

Some ideas, gathered from this thread:

- Use address book as Ocean DNS hosted somewhere
- Have Address book for each network
- Add bytecode hash to each address book entry to validate against the network that you interact with the correct contract
- Add signature of deployer/upgrader to validate the address

**Comment by aaitor** [comment]
IMO decoupling the ABI of the contract address is a necessary step. 
I like the approach we have in `squid-java` where we use the ABI coming from the keeper artifacts but not the addresses. It allows to use the same ABI to connect to any kind of network (same deployed contract version), independently if that network is Ocean official (`duero`, `nile`, `pacific`) or a bespoke network.

I guess the addressbook deployed by `dori` would be a good additional point. It could be used automatically by some applications (dapps for example) to connect to specific network contract addresses without user configuration.

In that case I would add as requirements for `dori`:

* The addressbook must be versioned and include the version number and when was updated
* The addressbook must be published automatically in a public repository owned by Ocean Protocol
* The addressbook must be served by HTTPS via a `oceanprotocol.com` domain

**Comment by alexcos20** [comment]
agreed, but in the same time we still need the option to run with a local address book (development, some uses cases of internal networks, etc).

**Comment by aaitor** [comment]
I think addressbook should be in all the cases optional to the dapp. It can be used to connect a network included in the list or not. Typically in that address book you shouldn't find local deployments, development, projects, etc.

**Comment by alexcos20** [comment]
that was my point also.  We can have a "global" address book for the public networks (duero,nile,pacific,etc) while for development networks we will use local files.

**Comment by ssallam** [comment]
Great stuff, I'm really glad to see this. The sooner we do this the better.

**Comment by H34D** [comment]
> IMO decoupling the ABI of the contract address is a necessary step.
> I like the approach we have in `squid-java` where we use the ABI coming from the keeper artifacts but not the addresses. It allows to use the same ABI to connect to any kind of network (same deployed contract version), independently if that network is Ocean official (`duero`, `nile`, `pacific`) or a bespoke network.

correct, this was my intention but this only works well for persistent networks not for development networks.

i would like to have a way to support all the networks and use cases.


> I guess the addressbook deployed by `dori` would be a good additional point. It could be used automatically by some applications (dapps for example) to connect to specific network contract addresses without user configuration.

exactly, this would make overwriting the address on the squid side (to support an unknown network) way more easier because squid has to separate the handling anyway.

> If the addressbook can be the "DNS" of our Smart Contract addresses will become a central piece to secure. A bad actor overwriting the addresses of the Smart Contracts (that could be automatically used by other ocean clients) could compromise the network. It's quite critical to think how to secure the addressbook.
> 
> In that case I would add as requirements for `dori` the following:
> 
> * The addressbook must be versioned and include the version number and when was updated
> * The addressbook must be published automatically in a public repository owned by Ocean Protocol
> * The addressbook must be served by HTTPS via a `oceanprotocol.com` domain
> * The addressbook needs to add the checksum and signature created by one publicly recognized Ocean Protocol account. This must allow clients to validate the authenticity of the addressbook.

we could use this address book as a form of DNS, marcus just proposed to add an hash of the bytecode of each contract at a specific address. Squid could fetch the bytecode and compare it to the hash of the address book. Or we could add a signature of the deployer/upgrader.

The possibles are endless and i want to move it this way.

**Comment by H34D** [comment]
> I think addressbook should be in all the cases optional to the dapp. It can be used to connect a network included in the list or not. Typically in that address book you shouldn't find local deployments, development, projects, etc.

i think development should go in as well, as long it stays local. If we put this on `oceanprotocol.com` like an DNS this will not work anymore.

**Comment by H34D** [comment]
> that was my point also. We can have a "global" address book for the public networks (duero,nile,pacific,etc) while for development networks we will use local files.

We could have different address books for different networks? Supporting another network would be writing another address book.

**Comment by H34D** [comment]
> ### Additional Ideas
> Some ideas, gathered from this thread:
> 
> * Use address book as Ocean DNS hosted somewhere
> * Have Address book for each network
> * Add bytecode hash to each address book entry to validate against the network that you interact with the correct contract
> * Add signature of deployer/upgrader to validate the address

i added a collection of ideas. Thats really comprehensive. Thanks for contributing all.

**Comment by H34D** [comment]
@alexcos20
